on:
  workflow_dispatch:
    inputs:
      release_name:
        description: Release title
        required: true
      release_body:
        description: Release notes body
        required: true
      release_html_url:
        description: Release URL
        required: false
  release:
    types: [published, created, released, edited]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Post to Discord (release event)
        if: ${{ github.event_name == 'release' }}
        uses: SethCohen/github-releases-to-discord@v1.20.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          username: "Overlay Bot"
          avatar_url: "https://cdn.discordapp.com/avatars/1459443855035207793/7c9cfca0e4c4516b30ee9ae695910df9.webp"
          content: "<@&1466344366045007894> A new version of Streak Overlay for Dead by Daylight has been released."

      - name: Post to Discord (manual dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: SethCohen/github-releases-to-discord@v1.20.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          username: "Overlay Bot"
          avatar_url: "https://cdn.discordapp.com/avatars/1459443855035207793/7c9cfca0e4c4516b30ee9ae695910df9.webp"
          content: "<@&1466344366045007894> A new version of Streak Overlay for Dead by Daylight has been released."
          release_name: ${{ inputs.release_name }}
          release_body: ${{ inputs.release_body }}
          release_html_url: ${{ inputs.release_html_url }}
